spring.application.name=ecgapp
spring.datasource.url=jdbc:postgresql://localhost:5432/MedAppDB
spring.datasource.username=postgres
spring.datasource.password=ege2509

spring.datasource.hikari.connection-timeout=20000
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG